// const users = [
//     {
//         id: 3098,
//         uid: '6e135d60-498e-4d4f-8b3d-88a199b26a15',
//         password: 'gyshLaMQ3q',
//         first_name: 'Brock',
//         last_name: 'Borer',
//         username: 'brock.borer',
//         email: 'brock.borer@email.com',
//         avatar:
//             'https://robohash.org/eaqueminimaincidunt.png?size=300x300\u0026set=set1',
//         gender: 'Male',
//         phone_number: '+299 367.195.6281 x909',
//         social_insurance_number: '141073908',
//         date_of_birth: '1977-11-10',
//         employment: {
//             title: 'Customer Legal Strategist',
//             key_skill: 'Organisation',
//         },
//         address: {
//             city: 'Lake Sydneychester',
//             street_name: 'Harber Mission',
//             street_address: '932 Cami Wells',
//             zip_code: '39799-5525',
//             state: 'Colorado',
//             country: 'United States',
//             coordinates: {
//                 lat: 69.1647012007497,
//                 lng: 52.858390146954235,
//             },
//         },
//         credit_card: {
//             cc_number: '4934157305711',
//         },
//         subscription: {
//             plan: 'Professional',
//             status: 'Pending',
//             payment_method: 'Debit card',
//             term: 'Monthly',
//         },
//     },
//     {
//         id: 1490,
//         uid: 'edf145cf-9ac0-424d-80ec-0140ee4c9e39',
//         password: '7sSKUnNaYb',
//         first_name: 'Kam',
//         last_name: 'Beier',
//         username: 'kam.beier',
//         email: 'kam.beier@email.com',
//         avatar: 'https://robohash.org/beataeinet.png?size=300x300\u0026set=set1',
//         gender: 'Genderqueer',
//         phone_number: '+218 1-610-957-8972 x3834',
//         social_insurance_number: '963831011',
//         date_of_birth: '1994-04-29',
//         employment: {
//             title: 'Construction Agent',
//             key_skill: 'Self-motivated',
//         },
//         address: {
//             city: 'North Demarcusfort',
//             street_name: 'Marquita Pine',
//             street_address: '228 Will Wall',
//             zip_code: '11736',
//             state: 'Missouri',
//             country: 'United States',
//             coordinates: {
//                 lat: 86.40512158205405,
//                 lng: -177.72364452684346,
//             },
//         },
//         credit_card: {
//             cc_number: '4470-8309-0408-9276',
//         },
//         subscription: {
//             plan: 'Essential',
//             status: 'Blocked',
//             payment_method: 'WeChat Pay',
//             term: 'Payment in advance',
//         },
//     },
//     {
//         id: 8013,
//         uid: 'b59e4797-5c32-4129-b846-3a34069d85c8',
//         password: 'CTuBQUJhig',
//         first_name: 'Hollis',
//         last_name: 'Swaniawski',
//         username: 'hollis.swaniawski',
//         email: 'hollis.swaniawski@email.com',
//         avatar: 'https://robohash.org/iustoquiaquo.png?size=300x300\u0026set=set1',
//         gender: 'Bigender',
//         phone_number: '+253 (833) 308-7538 x30532',
//         social_insurance_number: '271416307',
//         date_of_birth: '1976-03-17',
//         employment: {
//             title: 'Corporate Real-Estate Director',
//             key_skill: 'Work under pressure',
//         },
//         address: {
//             city: 'West Carey',
//             street_name: 'Altenwerth Dam',
//             street_address: '486 Myles Heights',
//             zip_code: '04406',
//             state: 'Colorado',
//             country: 'United States',
//             coordinates: {
//                 lat: 52.322070063036705,
//                 lng: 3.266901953713159,
//             },
//         },
//         credit_card: {
//             cc_number: '6771-8990-7039-6261',
//         },
//         subscription: {
//             plan: 'Basic',
//             status: 'Blocked',
//             payment_method: 'Visa checkout',
//             term: 'Monthly',
//         },
//     },
//     {
//         id: 9927,
//         uid: 'a7f8bcec-30fd-41f2-8ad0-8a692869859e',
//         password: 'orxEtn3BwK',
//         first_name: 'Ezekiel',
//         last_name: 'Buckridge',
//         username: 'ezekiel.buckridge',
//         email: 'ezekiel.buckridge@email.com',
//         avatar: 'https://robohash.org/estquidemut.png?size=300x300\u0026set=set1',
//         gender: 'Non-binary',
//         phone_number: '+1-868 (979) 799-2447 x5432',
//         social_insurance_number: '674125620',
//         date_of_birth: '1974-04-05',
//         employment: {
//             title: 'Construction Facilitator',
//             key_skill: 'Communication',
//         },
//         address: {
//             city: 'East Robin',
//             street_name: 'Wuckert Springs',
//             street_address: '841 Freddie Crossing',
//             zip_code: '21950',
//             state: 'New Jersey',
//             country: 'United States',
//             coordinates: {
//                 lat: -74.00693250553044,
//                 lng: -78.59921623048568,
//             },
//         },
//         credit_card: {
//             cc_number: '4161-6397-0263-8232',
//         },
//         subscription: {
//             plan: 'Business',
//             status: 'Blocked',
//             payment_method: 'Cash',
//             term: 'Monthly',
//         },
//     },
//     {
//         id: 1596,
//         uid: '15887069-1ff3-41db-9fa6-ba9c54797d96',
//         password: 'Yq3fQ1uonb',
//         first_name: 'Carlo',
//         last_name: 'Terry',
//         username: 'carlo.terry',
//         email: 'carlo.terry@email.com',
//         avatar:
//             'https://robohash.org/suscipitdoloribusquia.png?size=300x300\u0026set=set1',
//         gender: 'Polygender',
//         phone_number: '+225 414.697.5169 x74022',
//         social_insurance_number: '448301135',
//         date_of_birth: '1993-01-28',
//         employment: {
//             title: 'Customer Design Manager',
//             key_skill: 'Organisation',
//         },
//         address: {
//             city: 'Lake Christeen',
//             street_name: 'Latina Locks',
//             street_address: '8530 Aaron Groves',
//             zip_code: '25533-1833',
//             state: 'Arkansas',
//             country: 'United States',
//             coordinates: {
//                 lat: 10.848193891655413,
//                 lng: -10.316834223196679,
//             },
//         },
//         credit_card: {
//             cc_number: '5312-5436-6684-5111',
//         },
//         subscription: {
//             plan: 'Student',
//             status: 'Blocked',
//             payment_method: 'Bitcoins',
//             term: 'Full subscription',
//         },
//     },
//     {
//         id: 4456,
//         uid: 'a3ec9380-15fc-4cd9-b679-9760a81e5bf0',
//         password: 'HwzDd8T6bc',
//         first_name: 'Maximina',
//         last_name: 'Sipes',
//         username: 'maximina.sipes',
//         email: 'maximina.sipes@email.com',
//         avatar:
//             'https://robohash.org/necessitatibussequicommodi.png?size=300x300\u0026set=set1',
//         gender: 'Male',
//         phone_number: '+263 805-392-0056 x84239',
//         social_insurance_number: '954383006',
//         date_of_birth: '1993-03-02',
//         employment: {
//             title: 'Customer Designer',
//             key_skill: 'Confidence',
//         },
//         address: {
//             city: 'Spencerburgh',
//             street_name: 'Calvin Village',
//             street_address: '359 Green Lodge',
//             zip_code: '54964',
//             state: 'Louisiana',
//             country: 'United States',
//             coordinates: {
//                 lat: 51.024291149896385,
//                 lng: 45.796559266038145,
//             },
//         },
//         credit_card: {
//             cc_number: '4745130138106',
//         },
//         subscription: {
//             plan: 'Gold',
//             status: 'Blocked',
//             payment_method: 'Bitcoins',
//             term: 'Full subscription',
//         },
//     },
//     {
//         id: 4273,
//         uid: 'aaf0924a-90e1-4fb7-ace1-7396125156d7',
//         password: 'ewyTgoisDE',
//         first_name: 'Lawrence',
//         last_name: 'Reichel',
//         username: 'lawrence.reichel',
//         email: 'lawrence.reichel@email.com',
//         avatar:
//             'https://robohash.org/ipsumvoluptatemconsequatur.png?size=300x300\u0026set=set1',
//         gender: 'Male',
//         phone_number: '+263 1-962-218-0668 x7076',
//         social_insurance_number: '125915579',
//         date_of_birth: '1997-03-03',
//         employment: {
//             title: 'Senior Construction Assistant',
//             key_skill: 'Leadership',
//         },
//         address: {
//             city: 'Marcosmouth',
//             street_name: 'Garfield Terrace',
//             street_address: '27144 Simone Springs',
//             zip_code: '18786-5515',
//             state: 'Hawaii',
//             country: 'United States',
//             coordinates: {
//                 lat: -29.547900263499173,
//                 lng: -66.54868586022401,
//             },
//         },
//         credit_card: {
//             cc_number: '6771-8937-3644-2346',
//         },
//         subscription: {
//             plan: 'Gold',
//             status: 'Idle',
//             payment_method: 'Cheque',
//             term: 'Monthly',
//         },
//     },
//     {
//         id: 6983,
//         uid: '7f01b596-f4fc-4e00-a736-da629d8a10fb',
//         password: 'R6MbZPzYCL',
//         first_name: 'Logan',
//         last_name: 'Carter',
//         username: 'logan.carter',
//         email: 'logan.carter@email.com',
//         avatar:
//             'https://robohash.org/adipisciestdolorum.png?size=300x300\u0026set=set1',
//         gender: 'Agender',
//         phone_number: '+249 1-776-591-3677 x2361',
//         social_insurance_number: '650432529',
//         date_of_birth: '1989-06-24',
//         employment: {
//             title: 'Legal Administrator',
//             key_skill: 'Technical savvy',
//         },
//         address: {
//             city: 'Port Lacieton',
//             street_name: 'Giovanni Rapids',
//             street_address: '8986 Felicitas Garden',
//             zip_code: '93540',
//             state: 'West Virginia',
//             country: 'United States',
//             coordinates: {
//                 lat: -36.38570208710103,
//                 lng: 87.71119191819946,
//             },
//         },
//         credit_card: {
//             cc_number: '4993321346167',
//         },
//         subscription: {
//             plan: 'Basic',
//             status: 'Pending',
//             payment_method: 'WeChat Pay',
//             term: 'Payment in advance',
//         },
//     },
//     {
//         id: 9067,
//         uid: '476614ec-07e3-4c73-873f-828327cb9b92',
//         password: 'ZPG3xD7B6X',
//         first_name: 'Darius',
//         last_name: 'Berge',
//         username: 'darius.berge',
//         email: 'darius.berge@email.com',
//         avatar:
//             'https://robohash.org/doloremquenemodolor.png?size=300x300\u0026set=set1',
//         gender: 'Agender',
//         phone_number: '+266 563-910-2566 x7592',
//         social_insurance_number: '560889032',
//         date_of_birth: '1999-11-13',
//         employment: {
//             title: 'Education Officer',
//             key_skill: 'Leadership',
//         },
//         address: {
//             city: 'Ulrikeborough',
//             street_name: 'Rick Key',
//             street_address: '58236 Lyn Row',
//             zip_code: '64364',
//             state: 'Nevada',
//             country: 'United States',
//             coordinates: {
//                 lat: -33.614157418297864,
//                 lng: 175.9481609525949,
//             },
//         },
//         credit_card: {
//             cc_number: '6771-8959-9653-1031',
//         },
//         subscription: {
//             plan: 'Starter',
//             status: 'Active',
//             payment_method: 'Credit card',
//             term: 'Payment in advance',
//         },
//     },
//     {
//         id: 4453,
//         uid: '4713f7dd-5758-4876-971d-e00fca7bbaee',
//         password: 'gueI2lQOtE',
//         first_name: 'Wilbert',
//         last_name: 'Ward',
//         username: 'wilbert.ward',
//         email: 'wilbert.ward@email.com',
//         avatar:
//             'https://robohash.org/estvoluptascommodi.png?size=300x300\u0026set=set1',
//         gender: 'Agender',
//         phone_number: '+54 (113) 719-7081 x96017',
//         social_insurance_number: '262331150',
//         date_of_birth: '1966-07-26',
//         employment: {
//             title: 'Regional Advertising Director',
//             key_skill: 'Networking skills',
//         },
//         address: {
//             city: 'Lake Janyceville',
//             street_name: 'Sid Viaduct',
//             street_address: '9946 Skye Gateway',
//             zip_code: '23840',
//             state: 'New Jersey',
//             country: 'United States',
//             coordinates: {
//                 lat: -34.874710841332266,
//                 lng: -100.47253166626604,
//             },
//         },
//         credit_card: {
//             cc_number: '4649036882272',
//         },
//         subscription: {
//             plan: 'Essential',
//             status: 'Blocked',
//             payment_method: 'Credit card',
//             term: 'Annual',
//         },
//     },
//     {
//         id: 5468,
//         uid: '937f13fd-7074-4774-bd23-ad7e1187ad20',
//         password: '3zoDRU1MSO',
//         first_name: 'Phil',
//         last_name: 'Goldner',
//         username: 'phil.goldner',
//         email: 'phil.goldner@email.com',
//         avatar:
//             'https://robohash.org/sitvoluptatemipsum.png?size=300x300\u0026set=set1',
//         gender: 'Female',
//         phone_number: '+386 208.773.4703',
//         social_insurance_number: '707087862',
//         date_of_birth: '2002-02-11',
//         employment: {
//             title: 'Central Government Orchestrator',
//             key_skill: 'Communication',
//         },
//         address: {
//             city: 'Lake Jamika',
//             street_name: 'Runolfsdottir Mill',
//             street_address: '778 Alecia Stravenue',
//             zip_code: '80790-1030',
//             state: 'Texas',
//             country: 'United States',
//             coordinates: {
//                 lat: 68.58228990467362,
//                 lng: 41.28864710524468,
//             },
//         },
//         credit_card: {
//             cc_number: '4627-8448-5922-5274',
//         },
//         subscription: {
//             plan: 'Professional',
//             status: 'Pending',
//             payment_method: 'Google Pay',
//             term: 'Monthly',
//         },
//     },
//     {
//         id: 1317,
//         uid: 'a998491f-e7dc-4aeb-9979-f090ce28329f',
//         password: 'VYKSa8wMCE',
//         first_name: 'Lavern',
//         last_name: 'Bode',
//         username: 'lavern.bode',
//         email: 'lavern.bode@email.com',
//         avatar:
//             'https://robohash.org/repudiandaelaborumrecusandae.png?size=300x300\u0026set=set1',
//         gender: 'Bigender',
//         phone_number: '+224 532-164-9496',
//         social_insurance_number: '262292048',
//         date_of_birth: '1980-02-08',
//         employment: {
//             title: 'Accounting Specialist',
//             key_skill: 'Leadership',
//         },
//         address: {
//             city: 'Beatriceshire',
//             street_name: 'Sumiko Route',
//             street_address: '738 Fritz Glen',
//             zip_code: '76616-3265',
//             state: 'Louisiana',
//             country: 'United States',
//             coordinates: {
//                 lat: 35.64457308529927,
//                 lng: 23.765209486102037,
//             },
//         },
//         credit_card: {
//             cc_number: '5473-1054-7973-6211',
//         },
//         subscription: {
//             plan: 'Essential',
//             status: 'Active',
//             payment_method: 'Google Pay',
//             term: 'Monthly',
//         },
//     },
//     {
//         id: 8387,
//         uid: 'c2e6794b-d5f6-48fd-bf00-e5b592ac9575',
//         password: 'g3GnkOxzf7',
//         first_name: 'Albert',
//         last_name: 'Senger',
//         username: 'albert.senger',
//         email: 'albert.senger@email.com',
//         avatar: 'https://robohash.org/utquiafuga.png?size=300x300\u0026set=set1',
//         gender: 'Male',
//         phone_number: '+66 (331) 070-0730',
//         social_insurance_number: '711202069',
//         date_of_birth: '1986-02-16',
//         employment: {
//             title: 'Lead Banking Supervisor',
//             key_skill: 'Fast learner',
//         },
//         address: {
//             city: 'Lake Maryln',
//             street_name: 'Kuvalis Crossing',
//             street_address: '7779 Nona Plains',
//             zip_code: '31570-4812',
//             state: 'New Jersey',
//             country: 'United States',
//             coordinates: {
//                 lat: 74.89162552533713,
//                 lng: 74.6917179687118,
//             },
//         },
//         credit_card: {
//             cc_number: '5556-8884-3017-2341',
//         },
//         subscription: {
//             plan: 'Gold',
//             status: 'Active',
//             payment_method: 'Credit card',
//             term: 'Payment in advance',
//         },
//     },
//     {
//         id: 8521,
//         uid: '933ebf87-d304-4141-87a0-df13facf9132',
//         password: 'GNHm0T6pEQ',
//         first_name: 'Scottie',
//         last_name: 'Ondricka',
//         username: 'scottie.ondricka',
//         email: 'scottie.ondricka@email.com',
//         avatar:
//             'https://robohash.org/aliquamporronon.png?size=300x300\u0026set=set1',
//         gender: 'Agender',
//         phone_number: '+596 (251) 891-8270',
//         social_insurance_number: '488441148',
//         date_of_birth: '1975-05-03',
//         employment: {
//             title: 'Accounting Agent',
//             key_skill: 'Communication',
//         },
//         address: {
//             city: 'Port Harvey',
//             street_name: 'Lorretta Vista',
//             street_address: '71859 Nicolas Ramp',
//             zip_code: '85121',
//             state: 'Maryland',
//             country: 'United States',
//             coordinates: {
//                 lat: 17.890764168913663,
//                 lng: 172.82996889683756,
//             },
//         },
//         credit_card: {
//             cc_number: '4693599472907',
//         },
//         subscription: {
//             plan: 'Gold',
//             status: 'Idle',
//             payment_method: 'Credit card',
//             term: 'Full subscription',
//         },
//     },
//     {
//         id: 352,
//         uid: '3d7c0402-e8a3-4649-a3b7-80af4328ba04',
//         password: 'vCq3UVX6DQ',
//         first_name: 'Colin',
//         last_name: 'Johnson',
//         username: 'colin.johnson',
//         email: 'colin.johnson@email.com',
//         avatar:
//             'https://robohash.org/quibusdambeataequia.png?size=300x300\u0026set=set1',
//         gender: 'Bigender',
//         phone_number: '+674 1-926-463-3098 x16769',
//         social_insurance_number: '552046369',
//         date_of_birth: '1994-05-17',
//         employment: {
//             title: 'International Mining Agent',
//             key_skill: 'Proactive',
//         },
//         address: {
//             city: 'Batzburgh',
//             street_name: 'Gerlach Village',
//             street_address: '8605 Rohan Key',
//             zip_code: '42873-5949',
//             state: 'New Mexico',
//             country: 'United States',
//             coordinates: {
//                 lat: 28.717026485094337,
//                 lng: 87.91291911395427,
//             },
//         },
//         credit_card: {
//             cc_number: '6771-8922-2336-5499',
//         },
//         subscription: {
//             plan: 'Bronze',
//             status: 'Idle',
//             payment_method: 'Alipay',
//             term: 'Payment in advance',
//         },
//     },
// ]


// let content = ``

// console.log(users);

// users.forEach(user => {
//     content += `
//         <div class="grid-item">
//             <img src="${user.avatar}" alt="">
//             <h5>${user.first_name} ${user.last_name}</h5>
//             <p>${user.email}</p>
            
//         </div>
//       `
// })

// document.querySelector(".grid-container").innerHTML = content